CRITICAL - 2023-01-12 05:16:29 --> Class "App\Controllers\BaseController" not found
in APPPATH\Controllers\Home.php on line 5.
 1 SYSTEMPATH\Autoloader\Autoloader.php(282): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(857): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(444): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 05:22:14 --> Class "App\Controllers\BaseController" not found
in APPPATH\Controllers\Home.php on line 5.
 1 SYSTEMPATH\Autoloader\Autoloader.php(282): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(857): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(444): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 05:23:39 --> Class "App\Controllers\BaseController" not found
in APPPATH\Controllers\Home.php on line 5.
 1 SYSTEMPATH\Autoloader\Autoloader.php(282): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(857): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(444): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 05:25:00 --> Class "App\Controllers\BaseController" not found
in APPPATH\Controllers\Home.php on line 5.
 1 SYSTEMPATH\Autoloader\Autoloader.php(282): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(857): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(444): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-12 06:09:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-01-12 06:09:03 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `promotion` (`intitule`) VALUES (:intitule:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-12 06:10:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-01-12 06:10:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `promotion` (`intitule`) VALUES (:intitule:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-12 06:12:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-01-12 06:12:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `promotion` (`intitule`) VALUES (:intitule:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-12 06:13:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-01-12 06:13:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `promotion` (`intitule`) VALUES (:intitule:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-12 06:14:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\gestion_univ\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gestion_univ\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gestion_univ\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 C:\xampp\htdocs\gestion_univ\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\gestion_univ\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\gestion_univ\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\gestion_univ\app\Controllers\Home.php(13): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(907): App\Controllers\Home->index()
#8 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\gestion_univ\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gestion_univ\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-01-12 06:14:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `promotion` (`intitule`) VALUES (:intitule:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 06:26:55 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1577.
 1 SYSTEMPATH\BaseModel.php(1577): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Home.php(20): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 06:27:31 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1577.
 1 SYSTEMPATH\BaseModel.php(1577): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Home.php(20): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 06:28:02 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1577.
 1 SYSTEMPATH\BaseModel.php(1577): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Home.php(20): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-12 06:29:00 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1577.
 1 SYSTEMPATH\BaseModel.php(1577): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Home.php(20): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
